Db:
  Name: chatgpt
  Username: postgres
  Password: postgres

WsgiServer:
  Domain: api.chatgpt-ui.test
  DbUrl: postgres://postgres:postgres@chatgptdb:5432/chatgpt
  Django:
    Superuser:
      Username: admin
      Password: admin
      Email: admin@example.com
  AccountEmailVerification: none

WebServer:
  WsgiDomain: api.chatgpt-ui.test
  BackendUrl: http://chatgpt-ui-wsgi-server

Client:
  Domain: chatgpt-ui.test
  ServerUrl: http://chatgpt-ui-web-server
  NuxtPublicAppName: "ChatGPT UI"
