version: '3.8'
services:
  chatgptdb:
    container_name: chatgptdb
    image: postgres:12.9
    labels:
      kompose.controller.type: "statefulset"
      kompose.service.type: clusterip
    volumes:
      - chatgptdb:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB_FILE: /run/secrets/chatgpt-db/chatgpt-db
      POSTGRES_USER_FILE: /run/secrets/chatgpt-db-user/chatgpt-db-user
      POSTGRES_PASSWORD_FILE: /run/secrets/chatgpt-db-pass/chatgpt-db-pass
    secrets:
      - chatgpt-db
      - chatgpt-db-user
      - chatgpt-db-pass
    healthcheck:
      test: ["CMD-SHELL", "/bin/sh", "-c", "exec pg_isready -h 127.0.0.1"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - chatgpt-ui-network

  chatgpt-ui-wsgi-server:
    image: wongsaang/chatgpt-ui-wsgi-server:latest
    environment:
      APP_DOMAIN: "{{ .Values.django_domain }}"
      DB_URL: "{{ .Values.db_url }}"
      DJANGO_SUPERUSER_USERNAME: "{{ .Values.django_superuser_username }}"
      DJANGO_SUPERUSER_PASSWORD: "{{ .Values.django_superuser_password }}"
      DJANGO_SUPERUSER_EMAIL: "{{ .Values.django_superuser_email }}"
      SERVER_WORKERS: 3
      WORKER_TIMEOUT: 180
      ACCOUNT_EMAIL_VERIFICATION:  "{{ .Values.account_email_verification }}"
    ports:
      - '80:8000'
    depends_on:
      - chatgptdb
    networks:
      - chatgpt-ui-network

  chatgpt-ui-web-server:
    container_name: chatgpt-ui-web-server
    image: wongsaang/chatgpt-ui-web-server:latest
    labels:
      kompose.service.expose: "{{ .Values.django_domain }}"
      kompose.service.expose.ingress-class-name: "nginx"
      kompose.service.expose.tls-secret: "chatgpt-ui-web-server-secret"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    environment:
      BACKEND_URL: "{{ .Values.backend_url }}"
    ports:
      - '80:80'
    depends_on:
      - chatgptdb
    networks:
      - chatgpt-ui-network

  chatgpt-ui-client:
    container_name: chatgpt-ui-client
    image: wongsaang/chatgpt-ui-client:latest
    labels:
      kompose.service.expose: "{{ .Values.client_domain }}"
      kompose.service.expose.ingress-class-name: "nginx"
      kompose.service.expose.tls-secret: "chatgpt-ui-client-secret"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    environment:
      SERVER_DOMAIN:  "{{ .Values.server_domain }}"
      NUXT_PUBLIC_APP_NAME:  "{{ .Values.nuxt_public_app_name }}"
      NUXT_PUBLIC_TYPEWRITER:  false

    depends_on:
      - chatgpt-ui-web-server
    ports:
      - '80:80'
    networks:
      - chatgpt-ui-network

secrets:
  chatgpt-db:
    file: .origin/secret/db.txt
  chatgpt-db-user:
    file: .origin/secret/user.txt
  chatgpt-db-pass:
    file: .origin/secret/pass.txt

volumes:
  chatgptdb:
    driver: local

networks:
  chatgpt-ui-network:
    name: chatgpt-ui-network
    driver: bridge