version: '3.8'
services:
  chatgptdb:
    container_name: chatgptdb
    image: postgres:12.9
    labels:
      kompose.controller.type: "statefulset"
      kompose.service.type: nodeport
      kompose.service.nodeport.port: 32532
    volumes:
      - chatgptdb:/var/lib/postgresql/data
    ports:
      - "32532:5432"
    environment:
      POSTGRES_DB_FILE: /run/secrets/chatgpt-db/chatgpt-db
      POSTGRES_USER_FILE: /run/secrets/chatgpt-db-user/chatgpt-db-user
      POSTGRES_PASSWORD_FILE: /run/secrets/chatgpt-db-pass/chatgpt-db-pass
    secrets:
      - chatgpt-db
      - chatgpt-db-user
      - chatgpt-db-pass
    healthcheck:
      test: ["CMD-SHELL", "/bin/sh", "-c", "exec pg_isready -h 127.0.0.1"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - chatgpt-ui-network

  chatgpt-ui-wsgi-server:
    image: wongsaang/chatgpt-ui-wsgi-server:latest
    # labels:
    #   kompose.image-pull-secret: registry-auth-client-secret
    env_file:
      - .origin/config/wsgi.env
    environment:
      APP_DOMAIN: ${APP_DOMAIN}
      DB_URL: ${DB_URL}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
    ports:
      - '80:8000'
    depends_on:
      - chatgptdb
    networks:
      - chatgpt-ui-network

  chatgpt-ui-web-server:
    container_name: chatgpt-ui-web-server
    image: wongsaang/chatgpt-ui-web-server:latest
    labels:
      kompose.service.expose: "{{ .Values.server_host }}"
      kompose.service.expose.ingress-class-name: "nginx"
    env_file:
      - .origin/config/server.env
    environment:
      BACKEND_URL: ${BACKEND_URL}
    # configs:
    #   - source: chatgpt-ui-server-conf
    #     target: /etc/nginx/templates/default.conf.template
    ports:
      - '80:80'
    depends_on:
      - chatgptdb
    networks:
      - chatgpt-ui-network

  chatgpt-ui-client:
    container_name: chatgpt-ui-client
    image: wongsaang/chatgpt-ui-client:latest
    labels:
      kompose.service.expose: "{{ .Values.client_host }}"
      kompose.service.expose.ingress-class-name: "nginx"
      # kompose.image-pull-secret: registry-auth-client-secret
    env_file:
      - .origin/config/client.env
    environment:
      SERVER_DOMAIN: ${SERVER_DOMAIN}
      NUXT_PUBLIC_APP_NAME: ${NUXT_PUBLIC_APP_NAME}
      NUXT_PUBLIC_TYPEWRITER: ${NUXT_PUBLIC_TYPEWRITER}
      NUXT_PUBLIC_TYPEWRITER_DELAY: ${NUXT_PUBLIC_TYPEWRITER_DELAY}
    # configs:
    #   - source: chatgpt-ui-conf
    #     target: /etc/nginx/templates/default.conf.template
    depends_on:
      - chatgpt-ui-web-server
    ports:
      - '80:80'
    networks:
      - chatgpt-ui-network

# configs:
#   chatgpt-ui-conf:
#     file: chatgpt-ui.conf
#   chatgpt-ui-server-conf:
#     file: chatgpt-ui-server.conf

secrets:
  chatgpt-db:
    file: .origin/secret/db.txt
  chatgpt-db-user:
    file: .origin/secret/user.txt
  chatgpt-db-pass:
    file: .origin/secret/pass.txt

volumes:
  chatgptdb:
    driver: local

networks:
  chatgpt-ui-network:
    name: chatgpt-ui-network
    driver: bridge