apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.service: chatgpt-ui-wsgi-server
  name: chatgpt-ui-wsgi-server-deployment
  namespace: chatgpt-ui
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      cdk8s.io/metadata.addr: chatgpt-ui-wsgi-server-deployment-c8c5d759
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        cdk8s.io/metadata.addr: chatgpt-ui-wsgi-server-deployment-c8c5d759
        io.network/chatgpt-ui-network: "true"
    spec:
      automountServiceAccountToken: false
      containers:
        - env:
            - name: DJANGO_SUPERUSER_EMAIL
              value: "{{ .Values.WsgiServer.Django.Superuser.Email }}"
            - name: SERVER_WORKERS
              value: "3"
            - name: WORKER_TIMEOUT
              value: "180"
            - name: ACCOUNT_EMAIL_VERIFICATION
              value: "{{ .Values.WsgiServer.AccountEmailVerification }}"
            - name: APP_DOMAIN
              value: "{{ .Values.WsgiServer.Domain }}"
            - name: DB_URL
              value: "{{ .Values.WsgiServer.DbUrl }}"
            - name: DJANGO_SUPERUSER_USERNAME
              value: "{{ .Values.WsgiServer.Django.Superuser.Username }}"
            - name: DJANGO_SUPERUSER_PASSWORD
              value: "{{ .Values.WsgiServer.Django.Superuser.Password }}"
          image: wongsaang/chatgpt-ui-wsgi-server:latest
          imagePullPolicy: Always
          name: chatgpt-ui-wsgi-server
          ports:
            - containerPort: 8000
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          startupProbe:
            failureThreshold: 3
            tcpSocket:
              port: 8000
      dnsPolicy: ClusterFirst
      hostNetwork: false
      restartPolicy: Always
      securityContext:
        fsGroupChangePolicy: Always
        runAsNonRoot: false
      setHostnameAsFQDN: false
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: chatgpt-ui-wsgi-server-service
  namespace: chatgpt-ui
spec:
  externalIPs: []
  ports:
    - port: 80
      targetPort: 8000
  selector:
    cdk8s.io/metadata.addr: chatgpt-ui-wsgi-server-deployment-c8c5d759
  type: ClusterIP
