apiVersion: v1
kind: Service
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kompose.cmd: kompose convert -f docker-compose.yml -o ./.helm/templates
    kompose.service.expose: {{ .Values.client_domain }}
    kompose.service.expose.ingress-class-name: nginx
    kompose.service.expose.tls-secret: chatgpt-ui-client-secret
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: chatgpt-ui-client
  name: chatgpt-ui-client
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: chatgpt-ui-client
status:
  loadBalancer: {}
