apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kompose.cmd: kompose convert -f docker-compose.yml -o ./.helm/templates
    kompose.service.expose: {{ .Values.client_domain }}
    kompose.service.expose.ingress-class-name: nginx
    kompose.service.expose.tls-secret: chatgpt-ui-client-secret
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: chatgpt-ui-client
  name: chatgpt-ui-client
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chatgpt-ui-client
  strategy: {}
  template:
    metadata:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kompose.cmd: kompose convert -f docker-compose.yml -o ./.helm/templates
        kompose.service.expose: {{ .Values.client_domain }}
        kompose.service.expose.ingress-class-name: nginx
        kompose.service.expose.tls-secret: chatgpt-ui-client-secret
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/chatgpt-ui-network: "true"
        io.kompose.service: chatgpt-ui-client
    spec:
      containers:
        - env:
            - name: NUXT_PUBLIC_APP_NAME
              value: {{ .Values.nuxt_public_app_name }}
            - name: NUXT_PUBLIC_TYPEWRITER
              value: "false"
            - name: SERVER_DOMAIN
              value: {{ .Values.server_domain }}
          image: wongsaang/chatgpt-ui-client:latest
          name: chatgpt-ui-client
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
