apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o ./.helm/templates
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: chatgpt-ui-wsgi-server
  name: chatgpt-ui-wsgi-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chatgpt-ui-wsgi-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o ./.helm/templates
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/chatgpt-ui-network: "true"
        io.kompose.service: chatgpt-ui-wsgi-server
    spec:
      containers:
        - env:
            - name: ACCOUNT_EMAIL_VERIFICATION
              value: {{ .Values.account_email_verification }}
            - name: APP_DOMAIN
              value: {{ .Values.django_domain }}
            - name: DB_URL
              value: {{ .Values.db_url }}
            - name: DJANGO_SUPERUSER_EMAIL
              value: {{ .Values.django_superuser_email }}
            - name: DJANGO_SUPERUSER_PASSWORD
              value: {{ .Values.django_superuser_password }}
            - name: DJANGO_SUPERUSER_USERNAME
              value: {{ .Values.django_superuser_username }}
            - name: SERVER_WORKERS
              value: "3"
            - name: WORKER_TIMEOUT
              value: "180"
          image: wongsaang/chatgpt-ui-wsgi-server:latest
          name: chatgpt-ui-wsgi-server
          ports:
            - containerPort: 8000
          resources: {}
      restartPolicy: Always
status: {}
