apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o ./.helm/templates
    kompose.service.expose: {{ .Values.client_host }}
    kompose.service.expose.ingress-class-name: nginx
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: chatgpt-ui-client
  name: chatgpt-ui-client
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.client_host }}
      http:
        paths:
          - backend:
              service:
                name: chatgpt-ui-client
                port:
                  number: 80
            path: /
            pathType: Prefix
status:
  loadBalancer: {}
