apiVersion: v1
data:
  chatgpt-db-pass: SG8yME8yV0RLY01aY1JKcm5XQmw=
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: chatgpt-db-pass
  name: chatgpt-db-pass
type: Opaque
